# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'e1aae425-5549-4c28-b079-664bd316d71b'
  imageRepository: 'copyzillaweb'
  containerRegistry: 'copyzillaliveregistry.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/copyzilla_web/Dockerfile'
  tag: '$(Build.BuildId)'
  textEngineUrlArg: $(TEXT_ENGINE_URL_ARG)

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build
      inputs:
        command: build
        containerRegistry: $(dockerRegistryServiceConnection)
        repository: $(imageRepository)
        tags: $(tag)
        arguments: --label buildtype=nightly
    - task: Docker@2
      displayName: Push
      inputs:
        command: push
        containerRegistry: $(dockerRegistryServiceConnection)
        repository: $(imageRepository)
        tags: $(tag)
